### ISSUE TITLE
One-line installer bug

### ISSUE THREAD

**Issue by simonbugler** [pimoroni/speaker-phat#10]
The one-line installer has a bug. Whether you answer **y** or **n** it aborts. 

However after a few attempts answering y or n it does kick in. 

This has happened on 3 installs on 3 different pi's - haven't figured out the right combination.

**Comment by RogueM** [comment]
it sounds like there is some spurious entry being passed on, maybe a key repeat that makes it read 'yyyy' or something like that? do you ssh into the box or maybe use a bluetooth keyboard?

**Comment by simonbugler** [comment]
yes - these are all by ssh

**Comment by RogueM** [comment]
yes, it has happened to me before, particularly with Pi zeros... it's not really a bug in the installer per se, though I guess it could treat any input starting with 'y' as validation, rather than a literal parsing.

**Comment by simonbugler** [comment]
Maybe - not had the same issue with other Pimoroni one line installers

**Comment by RogueM** [comment]
I'll look into improving the handling of the user input for 'stuck keys' but it's definitely not a (new) 'bug', nor specific to the speakerphat installer, all our installers derive from the same template.

I have created myself an issue in the main 'get' installer repo so I don't forget about this:
https://github.com/pimoroni/get/issues/188
