### ISSUE TITLE
Software volume control

### ISSUE THREAD

**Issue by mikeparsons84** [pimoroni/speaker-phat#12]
I'm having some issues working out how to control volume of the speakerphat.

As the script disables the onboard sound and such Alsamixer won't now be connected to anything how have everyone managed to control volume?

**Comment by RogueM** [comment]
it depends on the application, some have software volume control of the stream they generate. I think it's possible to trick alsamixer to handle the speaker phat, but I'm not sure whether the VU meter would be affected, which may be weird.

You could also use something like the `mate-volume-control-applet` which rolls in pulseaudio to software volume control streams. You will need some ad hoc tweak to the alsa config however, but I think we have something somewhere that we were testing for this very purpose. But that requires a full desktop anyhow.

... I was going to have a look at that this week and see if software volume control could be provided without screwing everything up. I may be able to squeeze a couple of hours into that today.

**Comment by RogueM** [comment]
actually, we already have alsamixer volume control working... are you referring to the 'volumealsa' widget in the lxpanel in full desktop Raspbian? if so, it is specifically made for the on-board audio and it is completely useless to control anything but that.

to control volume, you can use `alsamixer` at the command line, it should work.

**Comment by mikeparsons84** [comment]
Brilliant, in that case it's down to my config which I've not set correctly.  When I installed the vumeter, the asound.conf is as follows.  Is there anything glaringly obvious why it wouldn't work?

Alsamixer says:
lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq AlsaMixer v1.0.28 qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
x Card: snd_rpi_hifiberry_dac                                                                                                                  F1:  Help               x
x Chip:                                                                                                                                        F2:  System information x
x View: F3: Playback  F4: Capture  F5: All                                                                                                     F6:  Select sound card  x
x Item:                                                                                                                                        Esc: Exit               x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                                                                                                                                      x
x                                                            This sound device does not have any controls.                                                             x


and my /etc/asound.conf says:

pcm.!default {
        type meter
        slave.pcm "softvol"
        #scopes.0 pivumeter
}

ctl.!default {
        type hw
        card 0
}

pcm.dmixer {
        type dmix
        ipc_key 1024
        ipc_perm 0666
        slave.pcm 'hw:0,0'
        slave {
                period_time 0
                period_size 1024
                buffer_size 8192
                rate 48000
        }
        bindings {
                0 0
                1 1
        }
}

ctl.dmixer {
        type hw
        card 0
}

pcm.softvol {
        type softvol
        slave.pcm "dmixer"
        control {
                name "PCM"
                card 0
        }
}

pcm_scope.pivumeter {
        type pivumeter
        decay_ms 500
        peak_ms 400
        brightness 128
        output_device speaker-phat
}

pcm_scope_type.pivumeter {
        lib /usr/local/lib/libpivumeter.so
}

pcm.pivumyeter {
        type meter
        slave.pcm 'hw:0,0'
        scopes.0 pivumeter
}
pcm.dsp0 pivumeter

**Comment by RogueM** [comment]
well, I'm not sure what you are trying to achieve... it seems you purposely disabled the VU meter?

if so then I think you are shooting yourself in the foot trying to start from our asound config - it would be immensely more straightforward to just set up a dmix with scontrol and not have a heap of cruft potentially throwing things out.

... maybe try this config, which _should_ be close to what I'd do if I didn't care about the VU on the speaker-phat:

https://github.com/pimoroni/picade-hat/blob/master/daemon/etc/asound.conf

**Comment by RogueM** [comment]
for what it's worth though, I'd say that changing `ctl.!default` to `ctl.dmixer` in your current config probably would fix the scontrol being stuck in limbo... but I would still recommend the asound I linked above if you really don't plan to make use of the VU..

**Comment by mikeparsons84** [comment]
Thank you for your time with this, much appreciated.  I commented out the VU because it wasn't working on initial install (it works if I run the test scripts (below) works absolutely fine, so I know the LED's are working when instructed.

So, I've just ran the full install again, with the standard asound.conf.  Alsa mixer is still struggling and have no volume control - it's obviously something I've done.  

Are there any other files to check at all that may need looking into?

**Comment by mikeparsons84** [comment]
so, this is what I get from the following command:

pi@raspberrypi:~/Pimoroni/speakerphat/python $ mpc volume
volume: n/a

**Comment by RogueM** [comment]
I would suspect that mpc spawns a pulseaudio daemon... we haven't got that far yet. I'll try it, but every use-case is a challenge and we've got a few on the operating table at the moment :/

**Comment by RogueM** [comment]
this is what I get with mpc:

>>>pi@zerowpi:~ $ mpc volume
error: Connection refused

... but firing up `alsamixer` works fine. If all you want is a cli command that you can call from a script (or manually), I could probably knock one up as we've got one for picade HAT that should be a doodle to repurpose. But if you don't get a PCM scontrol in alsamixer then that won't help - though I'm not quite sure why that would be the case for you.

**Comment by mikeparsons84** [comment]
Thank you, so I've got a but further and hit a wall.

For your information, at this stage:

aplay abc.wav #the VU meter works a treat with this
amixer  sset PCM,0 90% #this sets the volume a treat

the above work fine, but "mpc" does not work with alsamixer, nor the vumeter when streaming internet radio streams.  So I guess I'll have to live with the volume at max and no funky VU when streaming radio!?

**Comment by mikeparsons84** [comment]
OK, So for anyone wanting to do this, I've solved it with a workaround.

1) Don't use mpc
2) Use mplayer

So, mplayer with the (brilliant Pimoroni) standard install script works just fine.

a) You can stream from t'internet
b) The volume control works
c) The VU Meter works

WOO HOO

So, using 

a) mplayer -playlist http://www.radiofeeds.co.uk/bbcradio2.pls

and

b)  amixer  sset PCM,0 90%

to solve the above.

:)
