### ISSUE TITLE
no sound after latest raspbian update

### ISSUE THREAD

**Issue by jg00dman** [pimoroni/speaker-phat#14]
After latest update the speaker phat is silent... tried re-running the one liner but it doesn't fix it.

**Comment by Gadgetoid** [comment]
Is this running Raspbian Jessie with Pixel Desktop?

You should check for the existence of an `~/.asoundrc` file (aka `/home/pi/.asoundrc`)

**Comment by RobertFinger** [comment]
What does that last comment mean?  Should there be ~/.asoundrc or not? I am getting clicks but no sound from my speaker phat and I do have the file.  (in raspbian on raspi 3)

**Comment by Gadgetoid** [comment]
Ideally there should *not* be an `/home/pi/.asoundrc` since it overrides `/etc/asound.conf` and can bypass customisation.

You should look at `/etc/asound.conf` and also the output of `aplay -l` and `aplay -L`.

**Comment by Gadgetoid** [comment]
@jg00dman @RobertFinger any luck with this?
