### ISSUE TITLE
Why ping 8.8.8.8 to check connections?

### ISSUE THREAD

**Issue by oaigudmundsson** [pimoroni/speaker-phat#16]
Hello!

I just cannot install because of this error:

Checking environment...
We can't connect to the Internet, check your network!

May i suggest you remove this? Because some ppl (like me) use static routes and block 8.8.8.8. Why not just ping github or pimoroni.com?

`check_network() {
    sudo ping -q -w 10 -c 1 8.8.8.8 | grep "received, 0" &> /dev/null && return 0 || return 1
}

launch_url() {
    check_network || (error_box "You don't appear to be connected to the internet, please check your connection and try again!" && exit 1)
    if command -v xdg-open > /dev/null; then
        xdg-open "$1" && return 0
    else
        error_box "There was an error attempting to launch your browser!"
    fi
}

get_install() {
    check_network || (error_box "You don't appear to be connected to the internet, please check your connection and try again!" && exit 1)
    if [ "$1" != diagnostic ];then
        sysupdate && UPDATE_DB=true
    fi
    if ! command -v curl > /dev/null; then
        apt_pkg_install "curl"
    fi
    curl -sS https://get.pimoroni.com/$1 | bash -s - "-y" $2
    read -p "Press Enter to continue..." < /dev/tty
`}``

**Comment by RogueM** [comment]
if you know what you are doing you can use:
`curl https://get.pimoroni.com/speakerphat | bash -s - "-y"`
