### ISSUE TITLE
How to uninstall it and go back to default audio settings?

### ISSUE THREAD

**Issue by lorenzoromagnoli** [pimoroni/speaker-phat#17]
I need some help uninstalling the speaker phat settings and go back to default audio settings.

**Comment by Gadgetoid** [comment]
Copy `/etc/asound.conf` somewhere, and then delete it.

Make sure `dtparam=audio=on` is in `/boot/config.txt` and comment out the lines;

```
dtoverlay=i2s-mmap
dtoverlay=hifiberry-dac
```

And if you use the Pixel desktop you might want to re-add the volume control widget.

And if you want pulseaudio back (if you're using Raspbian < Stretch) you can (if it exists):

```
sudo mv /etc/xdg/autostart/pulseaudio.disabled /etc/xdg/autostart/pulseaudio.desktop
```
