### ISSUE TITLE
No Volume Control in Alsa-Mixer

### ISSUE THREAD

**Issue by exoqrtx** [pimoroni/speaker-phat#18]
I'm currently running a speaker phat on a pi3 running Arch linux so I couldn't use the standard installer and had to figure it out from the install script and implement manually.  The speaker itself is working fine but there's no volume control.  Opening up alsamixer just says "This sound device does not have any controls".  I'm not using the VU meter, nor planning to at this point, but I'd really love to be able to turn things down a bit.  I read through a previous issue (#12) that seemed somewhat similar but nothing there seemed to help.  Any assistance would be appreciated.  Let me know if you need any additional info.  Thanks!

Here's my /etc/asound.conf file:
```
pcm.!default {
    type hw
    card sndrpihifiberry
}

ctl.!default {
    type hw
    card sndrpihifiberry
}
```

**Comment by Gadgetoid** [comment]
Volume control requires the addition of the softvol plugin for ALSA.

See: https://alsa.opensrc.org/Softvol

**Comment by exoqrtx** [comment]
I got that to work after a bit of tinkering, thanks!
