### ISSUE TITLE
No ALSA audio devices detected....

### ISSUE THREAD

**Issue by kwalkerk** [pimoroni/speaker-phat#19]
I'm running a fresh install of Jessie on a Pi Zero W.  After running the speakerphat install program I get a message such as:  "No ALSA audio devices were detected.  Enable the internal audio device, or connect a USBO or HAT audio Device".   Have I missed something?

**Comment by soulmanpt** [comment]
I'm having the same issue.

**Comment by Gadgetoid** [comment]
Do you see any useful output relating to audio in `dmesg`. What's at the bottom of your `/boot/config.txt` file?

The installer should add a line `dtoverlay=hifiberry-dac` to the bottom of your `/boot/config.txt` which loads the `/boot/overlays/hifiberry-dac.dtbo` overlay and relevant audio drivers.

**Comment by Gadgetoid** [comment]
@kwalkerk @soulmanpt any progress/change/solution?

**Comment by Hotmud9** [comment]
I'm having the same issue. I looked at my boot/config.txt, and it's completely blank.
