### ISSUE TITLE
The setup script requires git

### ISSUE THREAD

**Issue by fstanis** [pimoroni/speaker-phat#20]
On Raspbian when git is not installed, the following error appears during installation:

```
All done!
bash: line 1115: git: command not found
bash: ./setup.sh: No such file or directory
```

**Comment by Gadgetoid** [comment]
Yes, this line in particular is where it grabs the Pi VU Meter code: `git clone --depth=1 https://github.com/$gitusername/pivumeter && cd ./pivumeter`

Looks like the installer needs to check for and install git where it's not available.
