### ISSUE TITLE
Driver initialization of PHat in Androidthings on rpi3

### ISSUE THREAD

**Issue by Sureshee** [pimoroni/speaker-phat#22]
Hi,
Can you give us some directions on how to initiate the driver for Android things. I don't need the LED, just the Audio is what i'm looking for.
Thanks in advance.
Regards
Suresh

**Comment by Gadgetoid** [comment]
Insofar as I can tell, there's no way to specify a device-tree overlay in AndroidThings /boot/config.txt.

I know very little about AndroidThings, I did a little searching but couldn't find a method for enabling hardware DACs. You would probably be better asking in Google's IoT Developers Community here: https://plus.google.com/communities/107507328426910012281

**Comment by Sureshee** [comment]
I, will check this info from the groups. 
Where can i find the hardware circuit diagram of this Speaker Hat.. 
Regards
Suresh
