### ISSUE TITLE
OSMC not supported?

### ISSUE THREAD

**Issue by acbakhit** [pimoroni/speaker-phat#23]
I received an error "Your operating system is not supported, sorry!" is OSMC really not supported? If not is there a list of supported OS's?

**Comment by LindseyB** [comment]
The latest Rasbian should work

**Comment by Gadgetoid** [comment]
OSMC is currently not supported with our one-line-installer, however it should be possible just to add `dtoverlay=hifiberry-dac` to `/boot/config.txt` and get sound output working.

**Comment by Gadgetoid** [comment]
Actually- I'm told you can just select "HiFiBerry" as the output device DAC in the OSMC settings menu.

**Comment by Gadgetoid** [comment]
Oh but in order to do that you must add `dtoverlay=hifiberry-dac` to `/boot/config.txt` first. D'oh!
