### ISSUE TITLE
wiringPi issue on raspberry pi zero

### ISSUE THREAD

**Issue by ghost** [pimoroni/speaker-phat#24]
The lights work just fine but when I try to play sound I get this error

Unable to determine hardware version. I see: Hardware  : BCM 2835

- expecting BCM2708 or BCM2709

If this is a genuine Raspberry Pi then please report this to projects@drogon.net... etc etc

This seems like a wiring pi issue. I used this repo https://github.com/pimoroni/speaker-phat

Is there something I need to do?

**Comment by Gadgetoid** [comment]
You may need to `sudo apt update` and `sudo apt upgrade` to make sure you have the latest packages and then run the installer again.

What OS are you running?

**Comment by ghost** [comment]
An upgrade to the latest lite OS fixed it! Thanks
