### ISSUE TITLE
No sound or lights on Pimeroni speaker

### ISSUE THREAD

**Issue by TheEndernaut** [pimoroni/speaker-phat#27]
I have tried several times with resoldering and desoldering my unit, and no matter what I do, I can't get the speaker or lights to work. I have been at this for days, with no prevail. Any help would be nice.

**Comment by TheEndernaut** [comment]
I have tried stopping PulseAudio, but nothing changes

**Comment by Gadgetoid** [comment]
Closing since this is ancient now, and I sincerely hope you got some help from our support team! Sorry for the delay.
