### ISSUE TITLE
CLI- only install - VU meter works but no sound

### ISSUE THREAD

**Issue by mpegg4** [pimoroni/speaker-phat#29]
Latest stretch install, CLI only (no GUI)
speakher phat bash installation successful
./test.sh VU activity works, but no sound

syslog shows following:

 [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon [etc]

Does speaker-phat need Raspbian stretch installed with GUI support?

**Comment by Gadgetoid** [comment]
Closing because this is nearly 2 years old and must have slipped my radar. Sorry! Please feel free to re-open if you're still having problems.
