### ISSUE TITLE
Raspberry Pi 4 support

### ISSUE THREAD

**Issue by tedwards-flf** [pimoroni/speaker-phat#30]
Does speakerphat work on Raspberry Pi 4? I only ask because I'm thinking of buying a raspberry pi 4 and to use other hats alongside speakerphat (including the seeed respeaker 4-mic array).

Thanks

**Comment by Gadgetoid** [comment]
Yes. It'll work fine on Pi 4/Buster, I've had a whole bunch of audio boards running lately. 😉
