### ISSUE TITLE
Audio device freezes after playing a file 

### ISSUE THREAD

**Issue by amicoleo** [pimoroni/speaker-phat#8]
Hello, 

I've succesfully installed the script at _https://get.pimoroni.com/speakerphat_  and than succesfully played an audio file (using SOX). 

But after that the device freezes (VU meter LEDs stuck on) and if I try playing a file again I get the following message printed on the terminal 

```
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
play FAIL formats: can't open output file `default': snd_pcm_open error: Device or resource busy
```

Any idea on how to fix that? 

------
**EDIT**

After the third reboot now everything seems to work fine.

**Comment by RogueM** [comment]
note that this repo no longer contain up-to-date code. The current code can be found at:
https://github.com/pimoroni/pivumeter

... if you ran our one-line-installer that is what you are using, and what would potentially be cause for the issue.

I'm going to tidy up this repo to be sure sno one relies on the code herein.

**Comment by amicoleo** [comment]
@RogueM Is pivumeter code supposed to configure audio for the speaker phat as well? Because I after running the script from there I still don't see any new audio device. 

From _aplay -l_


```
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by RogueM** [comment]
no, of course not - the whole point of it is that it does not care what audio device you use. You need to run the simple installer:

`curl https://get.pimoroni.com/speakerphat | bash`

**Comment by amicoleo** [comment]
Sorry, I was not clear in my post. I still have a problem with the shield. To recap. 

1. Clean install of Raspbian Linux raspberrypi 4.4.34-v7 on a Pi 3 Model B
2. I've installed the drivers per your instructions running the script at _https://get.pimoroni.com/speakerphat_
3. Installed sox (http://sox.sourceforge.net/) and libsox-fmt-mp3 for playing audio from the command line. 

If I now try reproducing an audio file, it works correctly. But sometimes after having played the file, current bash terminal gets stuck (no way to break from the audio reproduction message).  

```
 File Size: 5.06k     Bit Rate: 48.5k
  Encoding: MPEG audio    
  Channels: 1 @ 16-bit   
Samplerate: 22050Hz      
Replaygain: off         
  Duration: 00:00:00.84  

In:97.0% 00:00:00.81 [00:00:00.03] Out:35.7k [      |      ]        Clip:0    
Done.
```
VUmeter LEDs are still on after that, but I'm not actually interested in the vumeter, I pointed that out as just another signal that the shield was stuck. 

This issue sometimes happen after the first attempt to reproduce a file, sometimes after a few, but always happen eventually. 

Also, even after the device gets stuck, I can open another bash terminal and reproduce an audio file with no problem, just that the new terminal window will get stuck as well after that.

**Comment by RogueM** [comment]
try deleting/renaming /etc/asound.conf

... if the process still freezes then the problem is not linked to the vu code. If it does not then the pivumeter plugin is locking up. If the later then please post a new issue in the pivumeter repo.

to be honest, if sox locks up without pivumeter being involved then the issue likely is between sox and alsa, there is nothing particular about the dac we use and driver, which is a stock, widely used, from the upstream kernel.

Still, happy to try to help you, but we couod well be the wrong people to talk to (if pivumeter is not the culprit).

**Comment by amicoleo** [comment]
Hello, thanks. 

Renaming /etc/asound.conf did the trick. The process doesn't get stuck anymore. 

**EDIT**
But the audio playback quality is now very poor (pops at the beginning and the end of the file reproduction). 

I've tried using again the asound.conf file, deleting all the references to the vumeter 

```
pcm.!default {
        type meter
        slave.pcm "softvol"
}

ctl.!default {
        type hw
        card 0
}

pcm.dmixer {
        type dmix
        ipc_key 1024
        ipc_perm 0666
        slave.pcm 'hw:0,0'
        slave {
                period_time 0
                period_size 1024
                buffer_size 8192
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}

ctl.dmixer {
        type hw
        card 0
}

pcm.softvol {
        type softvol
        slave.pcm "dmixer"
        control {
                name "PCM"
                card 0
        }
}


```

And now the quality is good again, but the process is getting stuck again. 

On a sidenote, if the problem could be due to sox/alsa what's your recommended way to play mp3 with the speaker-phat?

**Comment by RogueM** [comment]
pops/clicks when the audio stream stops is not unusual. You may be able to avoid it by using playlists (sox seems to support m3u?). or try mpg123 to see if it behaves better.

... interesting that the asound dmixer seems to aleviate the problem. Not sure why it locks up though :/

**Comment by amicoleo** [comment]
I need single sound files to be played interactively, so I cannot use a playlist. And the noise is not just at the end of the sound but also when it starts, which is unfortunate. 

I'll try mpg123 as you mentioned. 

But otherwise, what's your recommended way to play mp3 files on a Pi 3 with the Speaker phat?

**Comment by RogueM** [comment]
I see that your file is a 22050Hz sample rate mono file? I think that is part of the problem and why a dmixer helps. You need a custom asound.conf that can handle the rate conversion - failing that then you need to find an mp3 player that handles conversion before opening a stream to ALSA.

**Comment by Gadgetoid** [comment]
There are tricks using pulseaudio, if I remember correctly, to hold the audio device open permanently.  We're also wondering if we can find a driver-level fix that would soften the pops.

**Comment by RogueM** [comment]
>>> If I now try reproducing an audio file, it works correctly. But sometimes after having played the file, current bash terminal gets stuck (no way to break from the audio reproduction message).

this is consistent with an issue that was raised elsewhere in one of our repo and has been traced back to alsa itself. see here: http://mailman.alsa-project.org/pipermail/alsa-devel/2017-March/118459.html
