### ISSUE TITLE
No VU meter or audio on speaker-phat

### ISSUE THREAD

**Issue by funk0id** [pimoroni/speaker-phat#9]
I've ran through the  https://get.pimoroni.com/speakerphat bash script a handful of times but keep hitting the same problem, I get no audio or VU. As soon as I move/rename the /etc/asound.conf I get audio back, but again no VU. 

I've gone through the process of setup.sh speaker-phat using pivumeter too and still have no joy.

Any ideas? Build is on a pi zero, running having installed all updates on jessie.

With asound.conf in place I get the following..

pi@local:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@local:~ $ speaker-test

speaker-test 1.0.28

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
Using device: speaker-phat
Channels count (1) not available for playbacks: Invalid argument
Setting of hwparams failed: Invalid argument

**Comment by RogueM** [comment]
is this on the full image of Raspbian Jessie or Lite? can you check whether you have an `.asoundrc` file in your home directory (`normally /home/pi/.asoundrc`). If so, delete it.

**Comment by RogueM** [comment]
you can't play (mono) 48000 files through the present configuration, so `speaker-test` wouldn't work. Try playing standard wav or mp3 files sampled at 44.1k (cd quality), or alternatively amend the asound.conf to match the rate you need.

... ultimately you should use an application that can handle on-the-fly sample rate conversion, or toggle into an environment fully in control of something like pulseaudio, which should do the trick if your preferred media player is not capable of handling sample conversion.

**Comment by RogueM** [comment]
we've change the default rate to 48000 - so if you re-run the installer `speaker-test` should work.

... that does not change the fact that `speaker-test`, `aplay`, and any other rudimentary playback applications are not going to fare well without getting dirty with configs, or converting your audio files pool.

**Comment by funk0id** [comment]
Hi, its running lite. Re-ran, same problem, I have no asoundrc file either. 

Soon as I move asound.conf, all is well with the speaker-phat again, minus the vu meter. 

edit - not sure if its because i'm in a different room too but since the last script run its gone seriously quiet!

**Comment by RogueM** [comment]
there is zero change to any part of the audio side - in fact, with no asound there is nothing at any level can could used to software control how loud it is.

I still don't know what you are using / intend to be using though... presumably you have other plans than play continuous pink noise in the background :)

**Comment by funk0id** [comment]
Got to love a bit of pink noise !! :)

I'm actually using it to output text to speech, doesn't have to be ear splitting but yeah, just seems very quiet!

Edit - Was your testing done from lite or using pixel / an alternative?

**Comment by funk0id** [comment]
So I started afresh tonight, totally clean build of jessie lite, all thats been done is ssh enabled then the speakerphat setup run again. 

I can get audio out of it now but still no vu :-/

**Comment by funk0id** [comment]
Well... the scripts don't work if you use lite, that's the problem.

I ran through the install on pixel, tested with cmus and it worked fine complete with vu. I then disable the boot into pixel and tested with cmus on the command line, everything worked!

So yes, I assume something is missing in the installation for people using lite.

**Comment by RogueM** [comment]
Hum, I have been using Lite exclusively with no trouble. There has been a number of critical updates since the Raspbian images has been released (and made, on the 20th Feb), are you sure you did `sudo apt-get upgrade` while in your Lite boot?

**Comment by funk0id** [comment]
Sure did, in fairness after I've had the trouble so I may have knocked something else out troubleshooting, but I tried  tried it the second time with little change and had the same problem. Working for me now though so all good, just ate some space up on the SD !

**Comment by RogueM** [comment]
speaker pHAT uses a sn3218 chip on the I2C bus... the most logical explanation I would have is that whatever application you use is operating under a specific user or group that has no access to the I2C (group).

**Comment by RogueM** [comment]
assuming you were using `espeak` (I still don't know though that would be the logical implied meaning of 'text to speech'), then we did found some issue with it, which seem to be fixed with the latest configuration that the `speakerphat` installer will install at this point.

... so worth trying if you start from scratch again in Lite, `espeak` certainly works now in Lite for me (with VU and dramatically improved playback).
